// src/ScrollyVideo.svelte
<script>
  import { onDestroy } from 'svelte';
  import ScrollyVideo from './ScrollyVideo';

  // variable to hold the DOM element
  let scrollyVideoContainer;

  // variable to hold the scrollyVideo object
  let scrollyVideo;

  // Store the props so we know when things change
  let lastPropsString = '';
  
  $: {
    if (scrollyVideoContainer) {
      // separate out the videoPercentage prop
      const { videoPercentage, ...restProps } = $$props;

      if (JSON.stringify(restProps) !== lastPropsString) {
        // if scrollyvideo already exists and any parameter is updated, destroy and recreate.
        if (scrollyVideo && scrollyVideo.destroy) scrollyVideo.destroy();
        scrollyVideo = new ScrollyVideo({ ...restProps, scrollyVideoContainer });

        // Save the new props
        lastPropsString = JSON.stringify(restProps);
      }

      // If we need to update the target time percent
      if (scrollyVideo && typeof videoPercentage === 'number' && videoPercentage >= 0 && videoPercentage <= 1) {
        scrollyVideo.setTargetTimePercent(videoPercentage);
      }
    }
  }

  // Cleanup the component on destroy
  onDestroy(() => {
    if (scrollyVideo && scrollyVideo.destroy) scrollyVideo.destroy();
  });
</script>

<div bind:this={scrollyVideoContainer} />

// src/ScrollyVideo.vue
<script>
import ScrollyVideo from './ScrollyVideo';

export default {
  data() {
    return {
      // variable to hold the scrollyVideo object
      scrollyVideo: null,

      // Store the props so we know when things change
      lastPropsString: '',
    };
  },
  methods: {
    refreshScrollyVideo(props) {
      // if scrollyvideo already exists and any parameter is updated, destroy and recreate.
      if (this.scrollyVideo) this.scrollyVideo.destroy();
      this.scrollyVideo = new ScrollyVideo({
        scrollyVideoContainer: this.$refs.containerElement,
        ...props
      });
    }
  },
  watch: {
    '$attrs': {
      handler: function() {
        // separate out the videoPercentage prop
        const { videoPercentage, ...restProps } = this.$attrs;

        if (JSON.stringify(restProps) !== this.lastPropsString) {
          this.refreshScrollyVideo(restProps);

          // Save the new props
          this.lastPropsString = JSON.stringify(restProps);
        }

        // If we need to update the target time percent
        if (this.scrollyVideo && typeof videoPercentage === 'number' && videoPercentage >= 0 && videoPercentage <= 1) {
          this.scrollyVideo.setTargetTimePercent(videoPercentage);
        }
      },
      deep: true
    }
  },
  mounted() {
    this.refreshScrollyVideo(this.$attrs);
  },
  unmounted() {
    if (this.scrollyVideo) this.scrollyVideo.destroy();
  }
}
</script>

<template>
  <div ref="containerElement" />
</template>
