// src/ScrollyVideo.jsx
import React, {
  forwardRef,
  useEffect,
  useState,
  useRef,
  useImperativeHandle,
} from 'react';
import ScrollyVideo from './ScrollyVideo';

const ScrollyVideoComponent = forwardRef(function ScrollyVideoComponent(
  {
    src,
    transitionSpeed,
    frameThreshold,
    cover,
    sticky,
    full,
    trackScroll,
    useWebCodecs,
    videoPercentage,
    onProgress,
    debug,
  },
  ref,
) {
  const containerElement = useRef(null);
  const scrollyVideoRef = useRef(null);
  const [instance, setInstance] = useState(null);

  const videoPercentageRef = useRef(videoPercentage);
  videoPercentageRef.current = videoPercentage;

  const onProgressRef = useRef(onProgress);
  onProgressRef.current = onProgress;

  // effect for destroy and recreate on props change (except video percentage)
  useEffect(() => {
    if (!containerElement.current) return;

    // if scrollyVideo already exists and any parameter is updated, destroy and recreate.
    if (scrollyVideoRef.current && scrollyVideoRef.current.destroy) {
      scrollyVideoRef.current.destroy();
    }

    const scrollyVideo = new ScrollyVideo({
      scrollyVideoContainer: containerElement.current,
      src,
      transitionSpeed,
      frameThreshold,
      cover,
      sticky,
      full,
      trackScroll,
      useWebCodecs,
      debug,
      onProgress: onProgressRef.current,
      videoPercentage: videoPercentageRef.current,
    });

    setInstance(scrollyVideo);
    scrollyVideoRef.current = scrollyVideo;
  }, [
    src,
    transitionSpeed,
    frameThreshold,
    cover,
    sticky,
    full,
    trackScroll,
    useWebCodecs,
    debug,
  ]);

  // effect for video percentage change
  useEffect(() => {
    // If we need to update the target time percent
    if (
      scrollyVideoRef.current &&
      typeof videoPercentage === 'number' &&
      videoPercentage >= 0 &&
      videoPercentage <= 1
    ) {
      if (trackScroll) {
        scrollyVideoRef.current.setScrollPercent(videoPercentage);
      } else {
        scrollyVideoRef.current.setTargetTimePercent(videoPercentage);
      }
    }
  }, [videoPercentage, trackScroll]);

  // effect for unmount
  useEffect(
    () => () => {
      if (scrollyVideoRef.current && scrollyVideoRef.current.destroy) {
        scrollyVideoRef.current.destroy();
      }
    },
    [],
  );

  useImperativeHandle(
    ref,
    () => ({
      setTargetTimePercent: scrollyVideoRef.current
        ? scrollyVideoRef.current.setTargetTimePercent.bind(instance)
        : () => {},
      setScrollPercent: scrollyVideoRef.current
        ? scrollyVideoRef.current.setScrollPercent.bind(instance)
        : () => {},
    }),
    [instance],
  );

  return <div ref={containerElement} data-scrolly-container />;
});

export default ScrollyVideoComponent;

// src/ScrollyVideo.vue
<script>
import ScrollyVideo from './ScrollyVideo.js';

export default {
  data() {
    return {
      // variable to hold the scrollyVideo object
      scrollyVideo: null,

      // Store the props so we know when things change
      lastPropsString: '',
    };
  },
  methods: {
    refreshScrollyVideo(props) {
      // if scrollyvideo already exists and any parameter is updated, destroy and recreate.
      if (this.scrollyVideo) this.scrollyVideo.destroy();
      this.scrollyVideo = new ScrollyVideo({
        scrollyVideoContainer: this.$refs.containerElement,
        ...props,
      });
    },
    setTargetTimePercent(...args) {
      if (this.scrollyVideo) this.scrollyVideo.setTargetTimePercent(...args);
    }
  },
  watch: {
    $attrs: {
      handler: function () {
        // separate out the videoPercentage prop
        const { videoPercentage, ...restProps } = this.$attrs;

        if (JSON.stringify(restProps) !== this.lastPropsString) {
          this.refreshScrollyVideo(restProps);

          // Save the new props
          this.lastPropsString = JSON.stringify(restProps);
        }

        // If we need to update the target time percent
        if (
          this.scrollyVideo &&
          typeof videoPercentage === 'number' &&
          videoPercentage >= 0 &&
          videoPercentage <= 1
        ) {
          if (restProps.trackScroll) {
            this.scrollyVideo.setScrollPercent(videoPercentage);
          } else {
            this.scrollyVideo.setTargetTimePercent(videoPercentage);
          }
        }
      },
      deep: true,
    },
  },
  mounted() {
    this.refreshScrollyVideo(this.$attrs);
  },
  unmounted() {
    if (this.scrollyVideo) this.scrollyVideo.destroy();
  },
};
</script>

<template>
  <div ref="containerElement" data-scrolly-container />
</template>
